name: esports_workout
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  path_provider: ^2.1.3
  sqflite: ^2.3.3+1
  url_launcher: ^6.3.0
  path: ^1.9.0


dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.jpg"
  min_sdk_android: 21 
  

flutter:
  uses-material-design: true

  assets:
  - assets/icons/logo.jpg
  - assets/icons/IconoLogo.jpg
  - assets/icons/background_login.png
  - assets/games/clashroyaleIcon.png
  - assets/games/leagueoflegendsIcon.png
  - assets/games/valorantIcon.png
  - assets/games/apexIcon.png
  - assets/games/counterstrikeIcon.png
  - assets/PreDefined_Exercises.json

  fonts:
  - family: You Blockhead #ClashRoyale
    fonts:
      - asset: assets/fonts/YouBlockheadOpen.ttf

  - family: Beaufort for LOL #LeagueOfLegends
    fonts:
      - asset: assets/fonts/BeaufortforLOL-Bold.ttf   

  - family: Valorant Font #Valorant
    fonts:
      - asset: assets/fonts/ValorantFont.ttf
      
  - family: Apex Legends Font #Apex Legends
    fonts:
      - asset: assets/fonts/Apex-Bold.ttf  

  - family: Counter-Strike #Csgo 2
    fonts:
      - asset: assets/fonts/cs2_regular.ttf
